### ISSUE TITLE
Deprecate get_expected_yield_for_sample

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/EGCG-Core#71]
function `get_expected_yield_for_sample` in `clarity` returns the Expected yield Q30.
This function should be deprecated and a more explicitly named one should be used.
It is mainly used in Analysis-Driver (https://github.com/EdinburghGenomics/Analysis-Driver)

**Comment by mwhamgenomics** [comment]
This function is no longer present in Analysis-Driver, and is now only used in the old auto-review in Project-Management, which is being removed. What should we do with this?
