### ISSUE TITLE
Optional script parameters

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/EGCG-Core#99]
It's possible to submit Slurm jobs with minimal parameters:

```bash
#!/bin/bash
#SBATCH --partition=partition_name
ls
```

It would make sense to be able to call `cluster_execute` with no parameters and submit a matching script, however at the moment this is not the case:

```python
>>> executor.cluster_execute('ls')
KeyError: 'job_name'
>>> executor.cluster_execute('ls', job_name='ls')
TypeError: _get_writer() missing 1 required positional argument: 'working_dir'
>>> executor.cluster_execute('ls', job_name='ls', working_dir='path/to/working_dir').join()
0
```

ls.slurm:
```bash
#!/bin/bash

#SBATCH --job-name="ls"
#SBATCH --cpus-per-task=1
#SBATCH --mem=2g
#SBATCH --partition=partition_name
#SBATCH --output=path/to/working_dir/ls.log

cd path/to/working_dir

ls
```

- [ ] We should check our current usages of executor and evaluate whether this would be a breaking change. If it is, we should look at alternatives, e.g. omitting Slurm script arguments that are present but set to `None`
- [ ] We should also do the same for PBS. It's possible that the two resource managers have different mandatory parameters

**Comment by tcezard** [comment]
Should we not drop the support for PBS scheduler?
It's unlikely that we will use it in the near future and I would prefer not to have to maintain the two.
We can revive it if required at a future date.
